# Generated by Django 5.0.1 on 2024-02-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(max_length=30)),
                ('meeting_time', models.CharField(default='11:30 - 12:30', max_length=50)),
                ('meeting_day', models.CharField(max_length=15)),
            ],
        ),
    ]
